[[mgr.prepend_keymap]]
on   = ["g", "s"]
run  = "cd ~/Desktop"
desc = "Go to ~/Desktop"

[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "cd E:/Projects"
desc = "Go to E:/Projects"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd 'D:\\'"

[[mgr.prepend_keymap]]
on = [ "g", "e" ]
run = "cd 'E:\\'"

[[mgr.prepend_keymap]]
on = [ "g", "f" ]
run = "cd 'F:\\'"

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"