[mgr]
show_hidden = true
linemode = "size"
ratio = [2, 3, 5]

[preview]
max_width = 1024
max_height = 1024
image_filter = "lanczos3"


[opener]

play = [
    { run = 'mpv %*', orphan = true }
]

edit = [
    { run = 'nvim %*', block = true }
]


open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ mime = "image/*", use = "play" },
	{ mime = "text/*", use = "edit" },
	{ name = "*.json", use = "edit" },		
	{ name = "*.html", use = [ "open", "edit" ] },
]